### ISSUE TITLE
default accounts.txt doesn't have AC config

### ISSUE THREAD

**Issue by Ferni7** [flightplan-tool/flightplan#18]
it gets created with palceholders for NH, KF, etc.. but not for AC. I added it in same pattern and works fine.

**Comment by jd20** [comment]
Did you ever confirm if this was due to the old credentials (which wouldn't have AC) being migrated? The AC account is only present in the template, it won't get added when the accounts.txt is created from an existing accounts.json.

**Comment by Ferni7** [comment]
No sorry, if you can't reproduce it don't worry/stress just close it, minor anyway :)

**Comment by jd20** [comment]
Yeah, I think it's working per design, closing.
