### ISSUE TITLE
Failure to install flightplan in MacOS Mojave

### ISSUE THREAD

**Issue by leungsc45** [flightplan-tool/flightplan#26]
Hi there!

I don't have any programming experience. Just encountered a problem while installing FlightPlan in MacOS Mojave v10.14. Already installed node, npm, XCode, and HomeBrew. The final few lines in my last attempt was -

sh: yarn: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! flightplan-tool@0.3.26 postinstall: `cd client && yarn`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the flightplan-tool@0.3.26 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Patrick/.npm/_logs/2018-11-22T15_19_46_025Z-debug.log

Thanks in advance!

**Comment by leungsc45** [comment]
Seemed it worked after installing yarn. Thanks anyways.

**Comment by jd20** [comment]
Cool, glad you got it working 👍 Technically, you can run flightplan without yarn (just npm), but some scripts in the `package.json` use yarn by default and would need to be updated.

**Comment by edzhang89** [comment]
I had the same issue in MacOS Mojave. The error was resolved once I installed yarn.
