### ISSUE TITLE
Request for adding

### ISSUE THREAD

**Issue by sxiii** [flightplan-tool/flightplan#28]
Greetings! I would like to request adding of some regular & low costing european air companies.

* Pobeda (pobeda.aero)
* Norwegian.com
* EasyJet
* RyanAir
* WizzAir
* AirBaltic
* LOT Polish Airlines

I would like to know if I can help with adding some of these.
Thanks!

**Comment by jd20** [comment]
Do you mean support award flights on these airlines, or actually scraping their websites for award inventory?

**Comment by jd20** [comment]
UA support is planned, I just don't have a firm date yet. Possibly this month.
