### ISSUE TITLE
Website version Vs GitHub version

### ISSUE THREAD

**Issue by johneakin** [flightplan-tool/flightplan#33]
Is there a different version on your website than in GitHub?

I don't see the GetRoutes functionality on GitHub
Also I tried passing a sample JSON from the Search API from the website as input to the GitHub version but get a map() error.

**Comment by jd20** [comment]
It is different, the front-end and API server have diverged significantly over the last couple months, which is why they're not compatible (as you've found). The Searcher and Parser's are same between both (so any scraper fixes get checked in here first).

**Comment by johneakin** [comment]
Thanks
Using the Master, When a search is made, should the extra filters for airline/flight etc show on the left panel? The code seems to be there, but they arent showing for me. (Although I havent scraped too much data)

**Comment by brianfife** [comment]
> It is different, the front-end and API server have diverged significantly over the last couple months

Is there any reason you are not open sourcing those components as well?  Searching in CLI for a visualization of the data via client/server is cumbersome vs. being able to search from the client/server implementation.  It'd almost be better off for the CLI search tool to just dump the results to console.
