### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by mlc130104** [flightplan-tool/flightplan#4]
Finished the first search last night, wanted to parse the results as instructed in the youtube vid. But got the following error:

TypeError: Cannot read property '1' of null

What did I missed to install? 

EDIT: Node version is v10.7.0

![capture](https://user-images.githubusercontent.com/7189975/43366438-c1b42c92-9370-11e8-9b7e-7fd295164690.PNG)

**Comment by jd20** [comment]
Looks like NH updated their parser. I've fixed with cf5443e87791f43bc44b89546ee3347b37d3aca6. Either update from GitHub, or `yarn upgrade flightplan-tool` or `yarn global upgrade flightplan-tool` (new package version is 0.1.11).
