### ISSUE TITLE
client: '/bin/sh: 1: yarn: not found'

### ISSUE THREAD

**Issue by maxiedaniels** [flightplan-tool/flightplan#41]
This is a weird one. Everything runs great *except* when I try to run `flightplan client`, I get `/bin/sh: 1: yarn: not found`. And yarn is definitely installed.

I do wonder if this is related to a previous bug I had, where running a flightplan search would tell me puppeteer does not have a chromium revision is not installed. I found a ton of threads about it, tried reinstalling (both local and global) puppeteer, yarn, everything. Turns out Flightplan was referencing the puppeteer in it's own node-modules folder rather than my home folder's node-modules folder. So I had to grab the .local-chromium folder from my own puppeteer and put it in flightplan's ./node-modules/puppeteer folder. (I still don't understand why this was happening??)

Is it possible that is happening in this case?

**Comment by jd20** [comment]
What operating system? What do you get if you run `yarn --version` or `which yarn`?

If you look at the directory the `flightplan` symlink resolves to (in your `yarn bin` directory), that's the `node_modules` it's using to load all of it's dependencies (such as puppeteer). If you start grabbing folders and manually messing around with the node_modules, there's a good chance that things will not be in sync correctly (the main reason to use yarn to install and upgrade flightplan, is that it checks the versions of everything and makes sure they're compatible).

Worst case, I'd uninstall flightplan (e.g. `yarn global remove flightplan`), and then re-install it (following instructions on the GitHub README).

**Comment by maxiedaniels** [comment]
Lubuntu 18.04. Yarn version = 1.15.2. `which yarn` doesn't return anything, strangely enough, even though typing `yarn` does show `yarn install v1.15.2` etc...

I followed the Flightplan installation perfectly multiple times (both using the npm install method and the yarn install method) and neither was working. I was always getting the error about Chromium.

I'll try removing Flightplan and redoing things again. Do you have any suggestions for completely removing yarn? I'm wondering if my yarn installation is messed up.

**Comment by maxiedaniels** [comment]
Fixed. I think it was a lot of different bugs that piled up with my installation of node and yarn. I ended up going through and removing every trace of yarn, and most things with node. I cleared out all path references to yarn, etc. Reinstalled from scratch without doing any of the hacky stuff, and this time it worked.

**Comment by jd20** [comment]
Got it, glad you figured it out! 👍

**Comment by maxiedaniels** [comment]
Thanks for the help :)
