### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by maxiedaniels** [flightplan-tool/flightplan#42]
Hi,

Due to weird bugs this week, I cleared all of flightplan and yarn, set node configs to default, and reinstalled fresh. Everything in terms of the flightplan install and then searching for rewards is working great.

But then after I run the server in one terminal and the client in another, my browser pops up to “localhost:3000” but I’m showing 502 bad gateway. The weird part is that I’m showing no warnings or errors in either the client window or server window. Do you have any suggestions?

**Comment by jd20** [comment]
Maybe something to do with your computer's network config? Try `127.0.0.1:3000` instead of localhost. Are you running any kind of VPN? Firewall?

**Comment by maxiedaniels** [comment]
I’ll try that. How can I bind to 0.0.0.0?

**Comment by jd20** [comment]
Which service? The client or server? And what exactly do you mean by bind it to 0.0.0.0, are you trying to make it accessible from other hosts?

**Comment by maxiedaniels** [comment]
I meant the client. I thought binding to 0.0.0.0 would be worth trying just to make sure there’s not some weird access issue. But 127.0.0.1 didn’t work either.

Are there lots stored anywhere for the client or server?

**Comment by maxiedaniels** [comment]
Whoops. It was a proxy extension in Chrome that had defaulted back to an old setting. My bad! Closing.
