### ISSUE TITLE
Can't Launch Server or Client

### ISSUE THREAD

**Issue by bryan7ran** [flightplan-tool/flightplan#6]
Hey Jason, great tool! I've been salivating over it all morning and have been running queries here and there.

I have collected 7 months' worth of data from 1/1/2019 CX HKG-SGN in Y, and it's all parsed, but I can't seem to launch the server and client tool (it freezes after "Success!" and there's an error when doing client). Do you have any suggestions? Running Windows 8.1 and here's my node.js command prompt:
![image](https://user-images.githubusercontent.com/23705878/44492164-bfb0cf00-a620-11e8-8205-d95ec4afac37.png)

It would be great to visualize these availabilities! Thanks!!

**Comment by jd20** [comment]
You need to keep the server running in the background. Run `flightplan server`, then open a new cmd.exe window, and run `flightplan client`. The error it's giving you is that it's can't find the server on port 3000, because you terminated it.

**Comment by bryan7ran** [comment]
Of course! A second window! Thanks, Jason! Looking forward to v2!
